# Miscelaneous
favicon: /favicon.ico

# fancybox gallery
fancybox: true

# main menu navigation
# ====================================
menu:
  home: /
  archive: /archives
  #category: /categories
  #tags: /tags
  about: /about

# site logo introduce and footer quote
# ====================================
logo: Ztopic
introduce: "practice makes perfect"
quote: "Love all, trust a few, do wrong to none.——William Shakespeare"

# social club
# ====================================
social:
  zhihu: https://www.zhihu.com/
  weibo: https://weibo.com
  github: https://github.com/
  steam:
  linkedin:
  facebook:
  twitter:
  douban:
  tumblr:
  instagram:
  stackoverflow:
  rss:

# third party services settings
# ===================================

#leanCloud
leancloud:
  app_id:
  app_key:

# comments
# Valine comment system. https://valine.js.org
valine:
  enable: false # if you want use valine, please set this value to true
  comment_name: 留言板 # your comment area title
  app_id:  # your leancloud appId
  app_key:  # your leancloud appKey
  notify: false # Mail notify
  verify: false # Verify code
  avatar: retro # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: 欢迎留言~ O(∩_∩)O # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

# Giscus
# Giscus Configration: https://giscus.app
giscus:
  enable: false
  comment_name: 欢迎留言~ # your comment area title
  repo: # giscus repo
  repo_id: # giscus repo-id
  category: # giscus data-category
  category_id: # giscus data-category-id
  mapping: # giscus data-mapping
  strict: 0 # giscus data-strict
  reactions_enabled: 0 # giscus data-reactions-enabled
  emit_metadata: 0 # giscus data-emit-metadata
  input_position: # giscus data-input-position
  theme: light # giscus data-theme
  lang: zh-CN # giscus data-lang
  loading: lazy # giscus data-loading

#disqus
disqus_shortname:


# ==================================
version: 1.1
# ==================================
